### ISSUE TITLE
reactions to a great project start

### ISSUE THREAD

**Issue by jmjpro** [Wildhoney/Switzerland#10]
@Wildhoney Great work! The project seems extremely promising. Some suggestions for improving:

Get people excited Switzerland
-------------------------------
* Add statistics about artifact sizes (gzipped & not)?
* Discuss strategies (or provide links to strategies that will work with Switzerland) for:
  * mobile
  * progressive
  * offline strategies (I see the the example support offline via ServiceWorker which is great)
  * universal rendering

Example
--------
* Consider following the guidelines from todomvc.com and submitting the example TODO app to them.
* The build.js in the example is almost 1.5 MB. Need to add justification for why or split it into vendor and app bundles.
* Example https://switzerland.herokuapp.com/ shows WSOD (white-screen-off-death) from Chrome on my Motorola Moto G running Marshmallow (6.0.2)

Development
-------------
* Add a section for contributing to the project. Explain that you're using the AVA test runner and the XO linter.

**Comment by Wildhoney** [comment]
Thank you so much for this @jmjpro!

I've actually had intentions of [creating a series of videos](https://github.com/Wildhoney/Switzerland-Example) but I've yet to get around to recording a single one. However my idea was to start with the basics, and then cover a whole array of different topics. I think it'd be a good way promote Switzerland, and so it's fairly high on my radar of things to do.

It's interesting that you mention universal rendering, because it's something I've been having many thoughts about. Of course Webcomponents aren't universal compatible, but there are [projects out there](https://github.com/pimterry/server-components) that attempt to do just this. As mentioned in `server-components` "Shadow DOM is challenging and less useful here, so not the main focus right now" which is certainly problematic, because whilst it's fairly straightforward, the shadow DOM part isn't so straightforward being entirely JavaScript based, whereas the advantage of the now deprecated [scoped CSS](https://vue-loader.vuejs.org/en/features/scoped-css.html) was that it was a lot easier to make universal.

The WSOD on your mobile was due to an issue with case-sensitivity in WebKit that [I raised a while ago](https://bugs.chromium.org/p/chromium/issues/detail?id=649279) &ndash; they've thankfully fixed it now, and [I reversed the patch I created a couple of days ago](https://github.com/Wildhoney/Switzerland/commit/1c872ae2480ff40980d861212643911a59079e64), although it's taking a little while for Chrome/Opera and other WebKit-based browsers to be updated on all devices.

Also the 1.5mb build is due to the example relying on some fairly large third-party libraries, which I could definitely improve on. I think the main culprits are: `webcomponents.js` for polyfilling Webcomponents mainly for Firefox, `ramda` which I could optimise to `import always from ramda/src/always` rather than `import { always } from 'ramda'` to allow for improved Webpack tree-shaking.

All in all, some great thoughts @jmjpro &ndash; any help will of course be much appreciated! If you would like to be a contributor, let me know and I'll add you to the project. Thanks!
