### ISSUE TITLE
MobX integration

### ISSUE THREAD

**Issue by d9k** [Wildhoney/Switzerland#14]
There are MobX mention at README.md but I haven't found mobx middleware at the repo.

Especially interested in https://github.com/mobxjs/mobx-state-tree integration

Thanks

**Comment by Wildhoney** [comment]
You've caught me out!

I was always meant to get around to adding the MobX integration, but never did. Do you know enough about MobX to begin integrating it into Switzerland? It shouldn't be that difficult, because all you'd need to do is add a handler for when the state changes, and then to invoke `render` passing in any necessary props.

For reference you could use the [Redux middleware](https://github.com/Wildhoney/Switzerland/blob/master/src/middleware/redux.js), which is very small.
