### ISSUE TITLE
Picodom → Ultradom

### ISSUE THREAD

**Issue by jorgebucaran** [Wildhoney/Switzerland#19]
Hi, @Wildhoney! 😃

Good job on this project! This issue is a friendly heads up! [Ultradom](https://github.com/jorgebucaran/ultradom) is the [continuation of and successor](https://github.com/jorgebucaran/ultradom/releases/tag/2.0.0) to Picodom. When you have time, could you please upgrade your package deps and add `ultradom` to your repo's tags?

**Comment by jorgebucaran** [comment]
I thought I could upgrade it myself, but without a good understanding of the code base, I think it would take me longer than I can manage. Fortunately, most changes are only cosmetic, in comments and in package.json.

In Ultradom, you don't need to keep track of the parent/container or previous node/tree. All you need is a new node/tree and the element you want to patch. This works because the first time you attempt to patch an element, Ultradom saves its virtual DOM in the element itself, allowing you to focus only on creating virtual nodes and using `patch` to update the DOM so it matches those virtual nodes.

Also, if you call patch without an element, an element is created for you, so you can do whatever you want with that element, append/insert/replace, etc.

The [release notes](https://github.com/jorgebucaran/ultradom/releases/tag/2.0.0) describe in detail these changes and if there's anything you think is missing, the [new documentation](https://github.com/jorgebucaran/ultradom/blob/master/README.md) does a much better job.

Hope this helps! 👋

**Comment by Wildhoney** [comment]
Issue much appreciated @jorgebucaran &mdash; thank you! I would have replied sooner, but I was away on holiday. I'll look to switch over later this week.

It looks as though I need to switch from `onremove` to `ondestroy` as well for my [event handling logic](https://github.com/Wildhoney/Switzerland/blob/master/src/middleware.js#L327-L330) because as far as I understand, `onremove` will **only** be invoked when the element itself is removed, but not when it's removed by a parent of the element.

Keep up the good work!

**Comment by jorgebucaran** [comment]
Yes! Summarizing:

> **onremove** is not called in the child elements of the removed element.
> **ondestroy** is called in elements that are removed or elements that will be removed as a result of their parent being removed.
